import type { CardTheme } from "../consts";

export const DEFAULT_KNOWLEDGE_CARD_THEME = "blackWhite";

export const KNOWLEDGE_CARD_THEME: Record<string, CardTheme> = {
  blackWhite: {
    textColor: "#000000",
    backgroundClass: "black-white",
    accentColor: "#000000",
    borderColor: "#e5e5e5",
    subtleColor: "#666666",
    decorativeLineColor: "#000000",
    numberColor: "#000000",
    backgroundColor: "#ffffff",
    titleColor: "#000000",
    titleFontSize: "clamp(24px, 4vw, 32px)",
    titleFontWeight: "bold",
    descriptionColor: "#666666",
    descriptionFontSize: "16px",
    sectionTitleColor: "#000000",
    sectionTitleFontSize: "20px",
    sectionTitleFontWeight: "600",
    keyPointColor: "#000000",
    keyPointFontSize: "14px",
    numberBackgroundColor: "#000000",
    numberTextColor: "#ffffff",
    numberFontWeight: "bold",
    decorativeLineWidth: "4px",
    decorativeLineHeight: "80px",
    linkColor: "#000000",
  },
  vintage: {
    textColor: "#262626",
    backgroundClass: "vintage",
    accentColor: "#404040",
    borderColor: "#d4d4d4",
    subtleColor: "#737373",
    decorativeLineColor: "#404040",
    numberColor: "#262626",
    backgroundColor: "#f5f5f5",
    gradient: "linear-gradient(135deg, #fafafa 0%, #f0f0f0 50%, #e5e5e5 100%)",
    titleColor: "#171717",
    titleFontSize: "clamp(26px, 4vw, 34px)",
    titleFontWeight: "bold",
    titleFontFamily: "'Playfair Display', 'Georgia', 'Times New Roman', serif",
    descriptionColor: "#525252",
    descriptionFontSize: "16px",
    descriptionFontFamily: "'Crimson Text', 'Georgia', serif",
    sectionTitleColor: "#262626",
    sectionTitleFontSize: "20px",
    sectionTitleFontWeight: "600",
    sectionTitleFontFamily:
      "'Playfair Display', 'Georgia', 'Times New Roman', serif",
    keyPointColor: "#404040",
    keyPointFontSize: "14px",
    keyPointFontFamily: "'Crimson Text', 'Georgia', serif",
    numberBackgroundColor: "#404040",
    numberTextColor: "#fafafa",
    numberFontWeight: "bold",
    numberFontFamily: "'Playfair Display', 'Georgia', 'Times New Roman', serif",
    decorativeLineWidth: "5px",
    decorativeLineHeight: "85px",
    fontFamily: "'Crimson Text', 'Georgia', serif",
    linkColor: "#262626",
  },
  glassmorphism: {
    textColor: "#ffffff",
    backgroundClass: "glassmorphism",
    accentColor: "rgba(255, 255, 255, 0.9)",
    borderColor: "rgba(255, 255, 255, 0.15)",
    subtleColor: "rgba(255, 255, 255, 0.8)",
    decorativeLineColor: "rgba(255, 255, 255, 0.9)",
    numberColor: "#ffffff",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    backgroundImage: "/cards/glass.webp",
    titleColor: "#ffffff",
    titleFontSize: "clamp(24px, 4vw, 32px)",
    titleFontWeight: "bold",
    descriptionColor: "rgba(255, 255, 255, 0.95)",
    descriptionFontSize: "16px",
    sectionTitleColor: "#ffffff",
    sectionTitleFontSize: "20px",
    sectionTitleFontWeight: "600",
    keyPointColor: "rgba(255, 255, 255, 0.95)",
    keyPointFontSize: "14px",
    numberBackgroundColor: "rgba(255, 255, 255, 0.2)",
    numberTextColor: "#ffffff",
    numberFontWeight: "bold",
    decorativeLineWidth: "4px",
    decorativeLineHeight: "80px",
    linkColor: "#ffffff",
  },
  freshNature: {
    textColor: "#262626",
    backgroundClass: "fresh-nature",
    accentColor: "#404040",
    borderColor: "rgba(255, 255, 255, 0.3)",
    subtleColor: "#525252",
    decorativeLineColor: "#404040",
    numberColor: "#262626",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    backgroundImage: "/cards/fresh.webp",
    titleColor: "#262626",
    titleFontSize: "clamp(24px, 4vw, 32px)",
    titleFontWeight: "bold",
    descriptionColor: "#262626",
    descriptionFontSize: "16px",
    sectionTitleColor: "#262626",
    sectionTitleFontSize: "20px",
    sectionTitleFontWeight: "600",
    keyPointColor: "#262626",
    keyPointFontSize: "14px",
    numberBackgroundColor: "#404040",
    numberTextColor: "#ffffff",
    numberFontWeight: "bold",
    decorativeLineWidth: "4px",
    decorativeLineHeight: "80px",
    linkColor: "#262626",
  },
};
